# Generated by Django 3.2.15 on 2022-08-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatar-g7397aeaf8_1280.png', upload_to='media/'),
        ),
    ]
